#! /bin/bash

PLOT="normalize.plot"

cp normalize-base.plot $PLOT

for i in $(seq $1 $2); do
	S=$((2 ** $i))
	T=$(($i-$1+1))
	echo -n "'data/normalize-real-$S.speedup.data' using 1:2 title 'real $S' with linespoints lw 2 lt $T" >> $PLOT
	if [ $i -ne $2 ]; then
		echo -n ", " >> $PLOT
	fi
done

echo "" >> $PLOT
echo "set termoption dashed" >> $PLOT
echo "set key right bottom" >> $PLOT
echo -n "plot " >> $PLOT

for i in $(seq $1 $2); do
	S=$((2 ** $i))
	T=$(($i-$1+5+$2-$1))
	echo -n "'data/transpose-complex-$S.speedup.data' using 1:2 title 'complex $S' with linespoints lw 2 lt $T" >> $PLOT
	if [ $i -ne $2 ]; then
		echo -n ", " >> $PLOT
	fi
done

#generate graph
gnuplot $PLOT
exit